version: 2

jobs:
  build:
    working_directory: ~/source
    docker:
      - image: circleci/ruby:2.5.0-node
        environment:
          RAILS_ENV: test
          RACK_ENV: test
      - image: circleci/postgres:10.4

    steps:
      - checkout

      - run: echo 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main' | sudo tee /etc/apt/sources.list.d/pgdg.list > /dev/null
      - run: wget --no-check-certificate -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O- | sudo -u root apt-key add -
      - run: sudo apt-get update
      - run: sudo apt-get install libpq-dev postgresql-client-10
      - run: pg_dump --version

  tests:
    working_directory: ~/source
    docker:
      - image: circleci/ruby:2.5.0-node
        environment:
          DATABASE_URL: postgres://test_u@localhost:5432/test_db
          BUNDLE_PATH: /home/circleci/source/vendor/bundle/ruby/2.5.0
          RAILS_ENV: test
          RACK_ENV: test
      - image: circleci/postgres:10.4
        environment:
          POSTGRES_USER: test_u
          POSTGRES_DB: test_db
      - image: redis:3.2.7
      - image: circleci/mongo:3.6.5

    steps:
      - attach_workspace:
          at: ~/source

      - run: pg_dump --version