jobs:
  build:
    working_directory: ~/source
    docker:
      - image: circleci/ruby:2.5.0-node
        environment:
          RAILS_ENV: test
          RACK_ENV: test

    steps:
      - checkout

      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "Gemfile.lock" }}

#      - run: echo 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main' | sudo tee /etc/apt/sources.list.d/pgdg.list > /dev/null
#      - run: wget --no-check-certificate -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O- | sudo -u root apt-key add -
#      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client

      - save_cache:
          key: v3-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
          - vendor/bundle

      - persist_to_workspace:
          root: ~/source
          paths:
            - .

  tests:
    working_directory: ~/source
    docker:
      - image: circleci/ruby:2.5.0-node
        environment:
          DATABASE_URL: postgres://test_u@localhost:5432/test_db
          BUNDLE_PATH: /home/circleci/source/vendor/bundle/ruby/2.5.0
          RAILS_ENV: test
          RACK_ENV: test
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: test_u
          POSTGRES_DB: test_db
      - image: redis:3.2.7
      - image: circleci/mongo:3.6.5

    steps:
      - attach_workspace:
          at: ~/source

      - run: pg_dump --version